### ISSUE TITLE
Idea: migrate -> begin and complete -> commit

### ISSUE THREAD

**Issue by chiroptical** [fabianlindfors/reshape#10]
What do you think about using the verbs from transactions in reshape?

**Comment by fabianlindfors** [comment]
I've been giving the command naming a lot of thought so this is a good suggestion. I'm not sure I want to adopt the naming used for transactions though to avoid any confusion.

Perhaps something like `reshape start` and `reshape complete`? Or maybe even `reshape migration start` and `reshape migration complete` to make it clearer and leave room for other commands. Not sure yet.

**Comment by chiroptical** [comment]
Yeah, I like `start/complete` in either form as well.

**Comment by fabianlindfors** [comment]
Hi again! This took a while but finally got around to touching up the CLI a bit. The commands are now.

- `reshape migration start`
- `reshape migration complete`
- `reshape migration abort`
- `reshape schema-query`

The old ones are still supported but marked as deprecated.

**Comment by chiroptical** [comment]
Very nice! I might start using this again in a different personal project. Very excited about these updates

**Comment by fabianlindfors** [comment]
Nice! Let me know if there is anything you're missing for that project :)
