### ISSUE TITLE
When are you planning your first production release?

### ISSUE THREAD

**Issue by Alttaf** [fabianlindfors/reshape#12]
### Great work

I really like the approach you have taken and am very interested on how things progress.  Would love to talk about this in more detail

Alttaf

**Comment by fabianlindfors** [comment]
Hi!

The one thing that's missing before I dare call Reshape production ready is real-life testing, so I'm basically hoping people will give Reshape a spin now and let me know how it goes.

There aren't any big features missing or any known bugs at the moment. If you'd like to use Reshape in a project, I'd be really happy to hear your feedback! :)

**Comment by Alttaf** [comment]
Hi fabian, We may give it a crack in the next few weeks.

**Comment by fabianlindfors** [comment]
Cool! Looking forward to your feedback. If you need help, run into any issues or are missing some feature, just create an issue here :)

**Comment by fabianlindfors** [comment]
Hi @Alttaf! Just wanted to note that I know consider ReshapeDB to be production ready. Haven't yet cut 1.0 but not because of any stability concerns, planning on doing that soon enough!
