### ISSUE TITLE
Quote identifier names

### ISSUE THREAD

**Issue by dmjef** [fabianlindfors/reshape#2]
Identifier names may contain characters that require them to be double-quoted. From looking at the code, it _appears_ that they are currently not quoted. Apologies if I'm wrong about this as I'm not very familiar with Rust.

**Comment by fabianlindfors** [comment]
Hi! This is a great idea. I'll update the queries soon. Thanks! :)

**Comment by fabianlindfors** [comment]
Done now with 9cd9bd395ba65222329ee7cd3dc6c388773b3d3e.

Thanks again, really appreciate the feedback!

**Comment by andygoossens** [comment]
Doesn't this make everything case sensitive?

**Comment by fabianlindfors** [comment]
Yes! I think that's desirable for Reshape, fewer surprises.
