### ISSUE TITLE
migration schema's view not exist when change the search_path to other schema

### ISSUE THREAD

**Issue by cksiow** [fabianlindfors/reshape#24]
Hi,

I'm having trouble with the migration process in my local PostgreSQL database. I've successfully created a migration folder and added the content of "migrations/1_create_users_table.toml" to it. When I run "reshape migration start --complete", it creates the "users" table in the "public" schema and the "migration_1_create_users_table" schema, along with a view of "users".

However, when I create another schema called "cktest", set the search path to "cktest", and restart the PostgreSQL service, remove "migration_1_create_users_table" and "reshape" schema to ensure it is reset to initial stage, the view of "users" is not created. I tried creating the "users" table manually in the "public" schema before running the migration again, and then the view was created and pointed to the "users" table in the "cktest" schema.

Below is the step
1. run ALTER DATABASE postgres SET search_path TO cktest;
2. restart my local postgresql service
3. remove migration_1_create_users_table and reshape schema
4. run again "reshape migration start --complete"

Can you please help me understand why this is happening and what I can do to resolve it? Thank you.

Postgres  version: 15

**Comment by fabianlindfors** [comment]
Hi!

How come you are changing the `search_path` manually here? For Reshape to work, you should only set it to the output of `reshape schema-query`. It's unfortunately not possible to use custom schemas and search paths with Reshape, as Reshape uses those to achieve zero-downtime migrations.

**Comment by cksiow** [comment]
Hi @fabianlindfors , meanwhile i can only use public schema as at now?

**Comment by fabianlindfors** [comment]
Sorry for the late reply but yes, Reshape assumes your actual table definitions live in the public schema
