### ISSUE TITLE
Comment regarding multi-tenancy

### ISSUE THREAD

**Issue by MahatmaFatalError** [fabianlindfors/reshape#4]
I stumbled over your blog https://fabianlindfors.se/blog/schema-migrations-in-postgres-using-reshape/ and unfortunately, there is no comment function (like Disqus), so I thought to comment here.

First of all, big appreciation! Great stuff you made ;) 

But I wanted to point your attention to the fact, that in real-life systems the schema might be already used for schema-based tenant separation, and also a connection pooler (HikariCP, Pg-Bouncer, PgPool-II, Heimdall) might interfere.
- https://blog.arkency.com/what-surprised-us-in-postgres-schema-multitenancy/
- https://blog.arkency.com/comparison-of-approaches-to-multitenancy-in-rails-apps/ 

So in order to address this, reshape would need to be aware of the tenant management and the application (more precisely the connection pooler) about the reshape-managed schemas.

**Comment by fabianlindfors** [comment]
Hi! I'm glad to hear you like Reshape and I hope you will find it useful :)

As you noted, the reliance on schemas for versioning rules out the usage of schemas for other things, like multi-tenancy. It's unfortunate but I haven't found a nicer way to implement versioning. Schemas simplify versioning a lot and lets the application be agnostic to Reshape, making it compatible with all ORMs and such. I'm not sure if it would be possible to support schema-based multitenancy, if you have an idea for how that could work I'd love to hear it.

Your point about connection poolers is great, hand't considered that. I should probably add a section in the documentation in the future detailing the pitfalls of using a connection pooler with Reshape.

Thanks for your input, much appreciated!

**Comment by MahatmaFatalError** [comment]
>  I'm not sure if it would be possible to support schema-based multitenancy, if you have an idea for how that could work I'd love to hear it.

Basically, the application (more precisely the app version) would need to know to which schema-version it is targeted, e.g. via the project organization, and reshape must respect the tenant identifier in a schema name.
For example, if the app starts with a parameter that contains the schema version, it could use to schema `{tenantId}-{version}` in its SQL statements. Of course, reshape needs to be done before the apps starts.
In essence, I doubt that a migration tool alone can deal with it, but rather a cooperation of the app together with the migration tool in the sense of general software architecture and devops processes.

> Your point about connection poolers is great, hadn't considered that. I should probably add a section in the documentation in the future detailing the pitfalls of using a connection pooler with Reshape.
Thanks for your input, much appreciated!


Happy to help ;)

**Comment by fabianlindfors** [comment]
> Basically, the application (more precisely the app version) would need to know to which schema-version it is targeted, e.g. via the project organization, and reshape must respect the tenant identifier in a schema name.
For example, if the app starts with a parameter that contains the schema version, it could use to schema {tenantId}-{version} in its SQL statements. Of course, reshape needs to be done before the apps starts.
In essence, I doubt that a migration tool alone can deal with it, but rather a cooperation of the app together with the migration tool in the sense of general software architecture and devops processes.

I see what you mean! Having Reshape generate a new schema for each tenant would definitely be possible but would require pretty deep coupling between Reshape and the application, something I'd like to avoid as far as possible. Based on this I don't think Reshape will support schema-based multi-tenancy unless it turns out to be a highly requested feature!

**Comment by fabianlindfors** [comment]
Closing as there are no plans to implement this for now
