### ISSUE TITLE
Inserting data?

### ISSUE THREAD

**Issue by chiroptical** [fabianlindfors/reshape#9]
I'll be honest. I am still very confused how I use this tool after making the migration. I am trying to remove the not-null constraint I added in the previous example,

```
reshape_example> SET search_path TO migration_6_make_name_null_again;
SET
Time: 0.001s
reshape_example> insert into users (name) values (null);
null value in column "name" of relation "users" violates not-null constraint
DETAIL:  Failing row contains (10, null, null).

Time: 0.005s
```

And the migration,

```
[[actions]]
type = "alter_column"
table = "users"
column = "name"

  [actions.changes]
  nullable = true
```

Is this expected to work?

**Comment by chiroptical** [comment]
I need to check quickly if this is because my first set of migrations were using the old version. One second!

**Comment by chiroptical** [comment]
I started from scratch and this behavior persists. The `id` column needs to carry over the `ALWAYS AS IDENTITY` and `PRIMARY KEY` constraints I guess?

**Comment by fabianlindfors** [comment]
Hi! Do you have a migration which alters the `id` column? Altering columns that are part of primary keys isn't supported at the moment (I should add that to the docs!)

**Comment by chiroptical** [comment]
I am not modifying the `id` column in the migration.

- migration: add table with `id` serial primary key and not null `name`
- migration: alter table, make `name` nullable
- set the search_path to the new migration
- try `insert into users (name) values (null);` and get the failure

**Comment by chiroptical** [comment]
Yeah, I'll drop them tomorrow. I had to switch machines.

**Comment by fabianlindfors** [comment]
I see the issue now! You haven't provided a `down` function for your second migration meaning Reshape doesn't know how to convert the null value into a value that is safe for the old schema. You could do something like this to for example fill in a default value in the old schema:

```
[[actions]]
type = "alter_column"
table = "users"
column = "name"

# Use 'N/A' for the old schema
down = "COALESCE(name, 'N/A')"

  [actions.changes]
  nullable = true
```

I've been wanting to add some explicit validation for these cases but haven't gotten around to it yet :)

**Comment by chiroptical** [comment]
This makes so much more sense now. Not sure if there is a better name here but I am starting to understand how this works

**Comment by fabianlindfors** [comment]
Glad to hear that! I could definitely do a better job making these things clearer. I've been working on some proper documentation but unfortunately I'm not a particularly good writer!

**Comment by chiroptical** [comment]
I can definitely help with that when I get further along. One of my plans is to write some blog posts or make videos on how to use this in a real project with a Haskell project.
